# dataset
data_filepath : "data/data.csv"
test_size : 0.2
random_state : 6
cols_to_drop : ["Unnamed: 0.1","Unnamed: 0"]

# hyperparameters
n_neighbors : 3

# model
model_filepath : "models/model.pkl"



